version: '3.9'

services:
  app:
    build:
      context: .
    container_name: category-api
    ports:
      - "8000:8000"
    command: npm start
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
